title: 'Jeevan'
description: "Mango"
baseurl: ""
url: ""

header_pages:
  - index.md
  - about.md
  # - contact.md

style: dark


# Build settings
markdown: kramdown
remote_theme: sleep-404/dark-theme-for-jekyll
theme: jekyll-theme-console