title: 'Jeevan'
description: "Mango"
baseurl: ""
url: ""

header_pages:
  - index.md
  - about.md
  # - contact.md

style: dark

listen_for_clients_preferred_style: true # false (default) or true
# Build settings
markdown: kramdown
# remote_theme: sleep-404/dark-theme-for-jekyll
theme: jekyll-theme-console